## ndarray 特性
- 可以進行元素級別的運算
- 僅能包含單一變數類型
- 可不規則使用索引值選取其中元素

In [3]:
my_list = [98, True, 'Ray']
for i in my_list:
    print(type(i))

<class 'int'>
<class 'bool'>
<class 'str'>


In [4]:
# 轉換成 ndarray 只會剩下一種型別
import numpy as np

arr = np.array(my_list)
for i in arr:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## 選擇 ndarray 的元素
- 索引值
- 判斷

In [7]:
arr = np.arange(11, 21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
# 索引值
print(arr[0])
print(arr[-1])
print(arr[::2])

# 特殊用法：用 list 就可以跳著選
print(arr[[0, 1, -1]])

11
20
[11 13 15 17 19]
[11 12 20]


In [15]:
# 直接判斷
print(arr > 15)
# 搭配判斷結果得到需要的 array
print(arr[arr > 15])

[False False False False False  True  True  True  True  True]
[16 17 18 19 20]


## 常用屬性
- .dtype 顯示 list 元素型別
- .shape 大小
- .size 幾個元素
- .ndim 多少維度
- .T 轉置矩陣

In [27]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(f'list 裝的型別為 {arr.dtype}')
print(f'list 形狀大小是 {arr.shape}')
print(f'list 有 {arr.size} 個元素')
print(f'list 有: {arr.ndim} 維')
print(f'轉置結果\n{arr.T}')
print(f'轉置結果形狀大小 {arr.T.shape}')

list 裝的型別為 int64
list 形狀大小是 (2, 3)
list 有 6 個元素
list 有: 2 維
轉置結果
[[1 4]
 [2 5]
 [3 6]]
轉置結果形狀大小 (3, 2)


## 常用方法
- .reshape 重新組合 n*m 矩陣
- .ravel 攤平多維矩陣成為一維
- .prod 取得乘積
- .sum 取得總和
- .where 依條件可以做一些事
- .concatenate 合併矩陣，可以依照 axis 調整合併的軸心
- .sort 整理

In [6]:
arr = np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# reshape: 2 * 5 矩陣
arr = arr.reshape(2, 5)
print(arr)
# ravel: 攤平
print(arr.ravel())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# .prod
# 全部數字相乘
print(arr.prod())
# 以欄位為軸心，每一列數字相乘
print(arr.prod(axis=0))
# 以列為軸心，每一欄數字相乘
print(arr.prod(axis=1))

3628800
[ 6 14 24 36 50]
[  120 30240]


In [22]:
# .where
# 如果只有條件，where 會回傳一個 tuple，代表 nonzero 的元素座標
np.where(arr > 2, 99, arr)

array([[ 1,  2, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [38]:
# .concatenate 用來合併矩陣，依照 axis（default 0）來決定軸心，axis=None 則攤平處理
arr_1 = np.arange(1, 11).reshape(2, 5)
# print(arr_1)
arr_2 = np.arange(11, 21).reshape(2, 5)
# print(arr_2)
flat = np.concatenate((arr_1, arr_2), axis=None)
print(flat)
vertical = np.concatenate((arr_1, arr_2), axis=0)
# print(vertical)
horizontal = np.concatenate((arr_1, arr_2), axis=1)
# print(horizontal)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
