## Numpy.r_

numpy 函式 r_ 終於被我破關！
感謝網路大大詳細解說！
https://www.ptt.cc/bbs/Python/M.1490169034.A.2D4.html

重點觀念：

- Numpy 要將陣列用向量、矩陣來思考
- 再來看英文文件恐怕要有線代的轉由名詞輔助
- r_ 底層還是用 python 函式，不是用 CPython 重刻，所以速度不會比較快，真正有價值的方法是矩陣組合 [x,y,z]

### 基本用法

1. 合併向量、矩陣
```python
np.r_([a],[b])
```

### 進階用法

`np.r_[]` 第一個參數可以放一個陣列，`[x,y]` 或 `[x,y,z]` 來決定矩陣組合

一開始，第一種進階用法我還看得懂，`[x,y]` 不就是 
- `x` 決定從第幾個維度開始合併
- `y` 決定新矩陣維度。

第二種階段用法`[x,y,z]`我就一直參透不了。
直到參考網路大大的解說，採用以下順序以及觀點

- `y` 先決定升級的矩陣維度
- `z` 決定每個數值要在第幾維並列
- `x` 決定兩個矩陣要從哪一個維度開始合併

有了這觀念，再看下面例子就懂了

1. x,y

A string integer specifies which axis to stack multiple comma separated arrays along. A string of two comma-separated integers allows indication of the minimum number of dimensions to force each entry into as the second integer (the axis to concatenate along is still the first integer).

範例：
```python
np.r_['0,2', [1,2,3], [4,5,6]]
```
> array([[1, 2, 3],
>       [4, 5, 6]])


2. x,y,z

A string with three comma-separated integers allows specification of the axis to concatenate along, the minimum number of dimensions to force the entries to, and which axis should contain the start of the arrays which are less than the specified number of dimensions. In other words the third integer allows you to specify where the 1’s should be placed in the shape of the arrays that have their shapes upgraded. By default, they are placed in the front of the shape tuple. The third argument allows you to specify where the start of the array should be instead. Thus, a third argument of ‘0’ would place the 1’s at the end of the array shape. Negative integers specify where in the new shape tuple the last dimension of upgraded arrays should be placed, so the default is ‘-1’.

搭配範例程式

```python
np.r_['0,2,0', [1,2,3], [4,5,6]]
```
>array([[1],
>       [2],
>       [3],
>       [4],
>       [5],
>       [6]])

```python
np.r_['1,2,0', [1,2,3], [4,5,6]]
```
>array([[1, 4],
>       [2, 5],
>       [3, 6]])
       

In [2]:
import numpy as np

In [7]:
np.r_['0,3', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [19]:
arr = np.r_['0,3,0', [1,2,3]]
print(arr)
print(arr.shape)

[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)


In [21]:
arr = np.r_['0,3,1', [1,2,3]]
print(arr)
print(arr.shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [22]:
arr = np.r_['0,3,2', [1,2,3]]
print(arr)
print(arr.shape)

[[[1 2 3]]]
(1, 1, 3)
