# Numpy 簡易說明
Python 有一種運算子叫做向量運算子可以做相加
舉例: [1,2,3] + [4,5,6] 結果是 [1,2,3,4,5,6]

但是數學向量運算還有乘除...
Numpy 這個套件就是要來解決這個問題
舉例：[1,2] * 2 結果就是 [2,4]
> 前提 [1,2] 型別是 ndarray

## 先來簡單範例
題目一：從公里轉成英里

In [2]:
kms = [1.6, 3, 5, 10, 42.195]
km_to_mile = 0.62137

In [3]:
# 使用 map
miles = map(lambda x: x * km_to_mile, kms)
print(list(miles))

[0.994192, 1.86411, 3.1068499999999997, 6.213699999999999, 26.21870715]


In [4]:
# 使用 Numpy 的 array
import numpy as np
# 1. list 先轉成 ndarray
km_array = np.array(kms)
# 2. 進行運算
miles = km_array * km_to_mile
miles

array([ 0.994192  ,  1.86411   ,  3.10685   ,  6.2137    , 26.21870715])

題目二：計算 BMI
> BMI 算法：體重(公斤)/身高平方(公尺)

In [4]:
heights = [173, 161, 166, 155, 180]
weights = [72, 59, 61.4, 50, 88]

In [26]:
height_array = np.array(heights)
weight_array = np.array(weights)

bmis = weight_array / (height_array / 100) ** 2
bmis

array([24.05693475, 22.76146754, 22.28189868, 20.81165453, 27.16049383])

題目三：[1, 2, 3, 4, 5] 取出大於 3 的數字 list

In [44]:
nums = np.array([1, 2, 3, 4, 5])
print(nums[nums > 3])

[4 5]


## 基礎建立 nd-array 方法
arange(), linspace(), ones(), zeros(), random.randint()
以上都可以指定型別

In [29]:
# arrange
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
# linspace 從 x 到 y 等距分為 z 份
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [33]:
# ones 產生個數 n 都是 1 的 nd-array
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [35]:
# zeros 產生個數 n 都是 0 的 nd-array
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
# 亂數產生, 1<=x<10, shape: 1 x 10
# 回傳是一個 array
arr = np.random.randint(1, 10, 10)
print(arr)

[3 5 5 2 3 4 9 5 2 4]


In [6]:
# 亂數產生，如果只有 low，沒有 high，產生範圍會自動變成 0<=x<low
np.random.randint(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# size 可以用 tuple 表示結果為 n * m 陣列，輸出 [[size=n*m]]
np.random.randint(2, size=(1, 2))

array([[0, 1]])

In [43]:
# 產生時指定型別
arr = np.ones(2, dtype=bool)
arr = np.zeros(3, dtype=int)
arr = np.ones(3, dtype=str)
# 特殊：np.zeros 指定 str，結果是' '
arr = np.ones(10, dtype=complex)
print(arr)

[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
